
# Site settings


title: Mourning Coffee
description: > # this means to ignore newlines until "baseurl:"
  Mourning Coffee is a podcast about grief
baseurl: "/"
url: "https://mourningcoffeepod.com"
author: Chris Calogero
email: chris.calogero@gmail.com
image: /assets/img/mourning-coffee-1400x1400.jpg
top_episodes:
  - 145
  - 121
  - 156
  - 153
  - 130
  - 104

mc_classics:
  - 190
  - 139
  - 105
  - 154
  - 137
  - 185

feedlimit: 200











twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/css

collections:
  episodes:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode_page
